// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserAuthApi.Data;

#nullable disable

namespace UserAuthApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260207100821_AddBookingTable")]
    partial class AddBookingTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UserAuthApi.Models.AdminInfo", b =>
                {
                    b.Property<string>("AdminId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Admin_id");

                    b.Property<string>("AMailId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("A_mail_id");

                    b.Property<string>("APassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("A_password");

                    b.HasKey("AdminId");

                    b.ToTable("Admin_info");
                });

            modelBuilder.Entity("UserAuthApi.Models.Booking", b =>
                {
                    b.Property<long>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BookingId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Address");

                    b.Property<bool>("Availed_Warranty")
                        .HasColumnType("bit");

                    b.Property<bool>("Battery_Replacement")
                        .HasColumnType("bit");

                    b.Property<string>("BookingStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Brake_Inspection")
                        .HasColumnType("bit");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Contact_Number");

                    b.Property<bool>("Cooling_System")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CurrentMileage")
                        .HasColumnType("int")
                        .HasColumnName("Current_Mileage");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Customer_id");

                    b.Property<string>("DescriptionOfIssues")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description_of_Issues");

                    b.Property<bool>("Electrical_System")
                        .HasColumnType("bit");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email_Address");

                    b.Property<string>("EmergencyContact")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Emergency_Contact");

                    b.Property<bool>("Engine_Check")
                        .HasColumnType("bit");

                    b.Property<bool>("Exhaust_System")
                        .HasColumnType("bit");

                    b.Property<string>("FuelType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Fuel_Type");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Full_Name");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Oil_Change")
                        .HasColumnType("bit");

                    b.Property<bool>("Pickup_Dropoff")
                        .HasColumnType("bit");

                    b.Property<string>("PreferredServicePackage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Preferred_Service_Package");

                    b.Property<string>("PreviousServiceHistory")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Previous_Service_History");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Registration_Number");

                    b.Property<string>("Selected_Dealer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Selected_Dealer_Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Slot")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Suspension_Check")
                        .HasColumnType("bit");

                    b.Property<bool>("Tire_Rotation")
                        .HasColumnType("bit");

                    b.Property<bool>("Transmission_Service")
                        .HasColumnType("bit");

                    b.Property<string>("TypeOfService")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Type_of_Service");

                    b.Property<short?>("VehicleModelYear")
                        .HasColumnType("smallint")
                        .HasColumnName("Vehicle_Model_Year");

                    b.Property<string>("VinChassisNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("VIN_Chassis_Number");

                    b.HasKey("BookingId");

                    b.ToTable("Booking");
                });

            modelBuilder.Entity("UserAuthApi.Models.CustomerInfo", b =>
                {
                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Customer_id");

                    b.Property<string>("CAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_address");

                    b.Property<long>("CContactInfo")
                        .HasColumnType("bigint")
                        .HasColumnName("c_contact_info");

                    b.Property<string>("CFirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_first_name");

                    b.Property<string>("CLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_last_name");

                    b.Property<string>("CMailId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_mail_id");

                    b.Property<string>("CMiddleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_middle_name");

                    b.Property<string>("CPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_password");

                    b.Property<string>("CUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("c_username");

                    b.Property<int>("LoyaltyPoints")
                        .HasColumnType("int")
                        .HasColumnName("loyalty_points");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("purchase_date");

                    b.Property<string>("VehicleModelYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("vehicle_model_year");

                    b.HasKey("CustomerId");

                    b.ToTable("Customer_info");
                });

            modelBuilder.Entity("UserAuthApi.Models.DealerInfo", b =>
                {
                    b.Property<string>("DealerId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Dealer_id");

                    b.Property<string>("DMailId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("d_mail_id");

                    b.Property<string>("DPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("d_password");

                    b.HasKey("DealerId");

                    b.ToTable("Dealer_info");
                });
#pragma warning restore 612, 618
        }
    }
}
